"""Delta Lake da plataforma — escrita por URI (qualquer camada/bucket)."""

from __future__ import annotations

from dataops_core.delta.health import (
    DEFAULT_MEDALLION_BUCKETS,
    DEFAULT_THRESHOLDS,
    bucket_usage,
    delta_uri_from_object_key,
    evaluate_health,
    growth_pct,
    is_ephemeral_delta_uri,
    is_temp_object_key,
    resolve_targets,
    table_stats,
)
from dataops_core.delta.io import (
    append,
    append_bronze,
    cleanup_log,
    count_key_duplicates,
    count_rows,
    dedupe_table,
    delta_uri,
    is_delta_table,
    merge,
    merge_bronze,
    optimize_compact,
    overwrite,
    overwrite_bronze,
    resolve_s3_ca_bundle,
    resolve_s3_ssl_verify,
    s3_client,
    storage_options,
    uri_from_parts,
    vacuum,
    vacuum_bronze,
)

__all__ = [
    "DEFAULT_MEDALLION_BUCKETS",
    "DEFAULT_THRESHOLDS",
    "append",
    "append_bronze",
    "bucket_usage",
    "cleanup_log",
    "count_key_duplicates",
    "count_rows",
    "dedupe_table",
    "delta_uri",
    "delta_uri_from_object_key",
    "evaluate_health",
    "growth_pct",
    "is_delta_table",
    "is_ephemeral_delta_uri",
    "is_temp_object_key",
    "merge",
    "merge_bronze",
    "optimize_compact",
    "overwrite",
    "overwrite_bronze",
    "resolve_s3_ca_bundle",
    "resolve_s3_ssl_verify",
    "resolve_targets",
    "s3_client",
    "storage_options",
    "table_stats",
    "uri_from_parts",
    "vacuum",
    "vacuum_bronze",
]
